//! The crash schedules are read, and a campaign that shrank fails here.
//!
//! Invariant: **a campaign that reports fewer cut points than it used to has
//! stopped testing something, and that is a failure rather than a diff.**
//! `tests/crash/README.md` has said so since the directory was made, and until
//! this file nothing acted on it. The first version of the DELETE campaign
//! reported 127 cut points while causing thirteen crashes, because a crash
//! armed at a read did nothing and the failpoint counter was already past the
//! low numbers before the run began. That is the shape being guarded: the file
//! still parses, the run still exits 0, and the number quietly falls.
//!
//! A diff cannot hold it. The schedules are regenerated by the campaigns that
//! write them, so a shrinking campaign rewrites its own record - the evidence
//! and the thing the evidence is about are the same file. The floor below is
//! the second copy, in a place a campaign does not write.
//!
//! **Why the floors are here and not in the files** (task-2066 §4.4.9). A
//! number in the file is what the last run produced, and the last run is what
//! is under suspicion. A number in this source is what a human accepted, and
//! raising it is an edit somebody makes on purpose.
//!
//! The second half of this file is about the bytes rather than the numbers. The
//! campaigns write LF; `core.autocrlf` is true on the machine releases are cut
//! on, so git used to check these files out with CRLF and every run of the
//! durability tier left twenty-one files modified with an empty diff. The
//! review signal the directory exists for was noise, and `packaging/ship.ps1`
//! and `cargo publish` both refuse a dirty tree. `.gitattributes` now carries
//! `/tests/crash/** text eol=lf`; `no_report_carries_a_carriage_return` is what
//! notices if that rule is ever dropped.

use std::path::{Path, PathBuf};

use inillucent_compat::workspace_root;

/// One report, and the smallest count a run of it may produce.
struct Floor {
    /// The file's name under `tests/crash/`.
    name: &'static str,
    /// How the count is read out of the file.
    shape: Shape,
    /// The count below which the campaign has stopped testing something.
    ///
    /// Recorded from the file as it stood at `8607adf`, which is the run the
    /// task-2066 review read. A campaign that legitimately covers more cut
    /// points raises this in the same commit; one that covers fewer is the
    /// defect this file is for.
    least: usize,
}

/// How a report states how much it covered.
#[derive(Clone, Copy)]
enum Shape {
    /// `cut points: N, ...` on the first line.
    CutPoints,
    /// `# N cuts: ...` on the first line.
    HashCuts,
    /// No header, so the rows are the count. The first line is a column
    /// heading when `heading` is true.
    Rows { heading: bool },
}

/// Every schedule, with the count it may not fall below.
///
/// `allocation.txt` is deliberately absent. It records `points: 0` because the
/// shipping engine's write path makes no allocation the failpoint counts, so a
/// floor on it would be a floor on zero - which is what
/// `the_allocation_report_says_why_it_is_empty` asserts instead, and what
/// §4.4.12 files as work rather than as a number to guard.
///
/// **Ten floors were lowered by the change that let readers read beside a
/// write.** An open, and a reader catching up with the log, used to cut a torn
/// tail off the log as soon as they had replayed it: an open of the segment, a
/// truncate, a sync and a look for later segments, at every open a campaign
/// makes. Both now hold only SHARED there, beside a writer that may be
/// appending, so they leave the cut to the next connection that replays while
/// holding the writer's lock (`Database::with_writer_slot`). Those calls are
/// the cut points that went: five to eight per campaign, all of them before the
/// commit, with every state and every recovered answer unchanged.
const FLOORS: [Floor; 20] = [
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 88 cut points
    // became 80. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 80 cut points became 76 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 76
    // cut points, and 63 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 63 calls became 59. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 57 cut points became 59, and
    // 57 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 57 cut points before both, 54 with
    // the meta slots change alone, 57 with the header change alone, and 54 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` by
    // putting the sync back: 54 cut points with it and 53 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Ten fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 53 cut points before the change and 43 after. Every cut point
    // still recovers to a state the campaign accepts.
    // **Two fewer since a statement that only read keeps SHARED for the next
    // one (task-2197).** The statement after it takes no lock and reads no
    // meta record, and a lock and a read are each a cut point. Measured
    // through the campaign with the lease switched off: 43 cut points, and 41
    // with it. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-crash.txt",
        shape: Shape::CutPoints,
        least: 41,
    },
    // **The same workload with the commit's log sync left to the fold that
    // follows it, which is what the command line's `exec` runs under
    // (task-2191).** 51 cut points when it was added: the log is not synced at
    // the commit or in the fold, and the fold runs inside the statement. The
    // unarmed run is the only acknowledged one, because the statement returns
    // once the fold is done. Breaking the mode so it acknowledges without
    // folding fails the campaign with an acknowledged commit lost.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 51 cut points before the change and 39 after. Every cut point
    // still recovers to a state the campaign accepts.
    // **Two fewer since a statement that only read keeps SHARED for the next
    // one (task-2197).** The statement after it takes no lock and reads no
    // meta record, and a lock and a read are each a cut point. Measured
    // through the campaign with the lease switched off: 39 cut points, and 37
    // with it. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "delete-fold-crash.txt",
        shape: Shape::CutPoints,
        least: 37,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 88 cut points
    // became 80. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 80 cut points became 76 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 76
    // cut points, and 63 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 63 calls became 59. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 57 cut points became 59, and
    // 57 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `delete-full-crash.txt`, which runs the same workload, by putting each
    // change back in turn: 57 cut points before both, 54 with the meta slots
    // change alone, 57 with the header change alone, and 54 with both. Every
    // cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` on
    // `delete-full-crash.txt`, which runs the same workload, by putting the
    // sync back: 54 cut points with it and 53 without. Every cut point still
    // recovers to a state the campaign accepts.
    // **Ten fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 53 cut points before the change and 43 after. Every cut point
    // still recovers to a state the campaign accepts.
    // **Two fewer since a statement that only read keeps SHARED for the next
    // one (task-2197).** The statement after it takes no lock and reads no
    // meta record, and a lock and a read are each a cut point. Measured
    // through the campaign with the lease switched off: 43 cut points, and 41
    // with it. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-disk-full.txt",
        shape: Shape::CutPoints,
        least: 41,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 88 cut points
    // became 80. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 80 cut points became 76 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 76
    // cut points, and 63 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 63 calls became 59. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 57 cut points became 59, and
    // 57 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `delete-full-crash.txt`, which runs the same workload, by putting each
    // change back in turn: 57 cut points before both, 54 with the meta slots
    // change alone, 57 with the header change alone, and 54 with both. Every
    // cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` on
    // `delete-full-crash.txt`, which runs the same workload, by putting the
    // sync back: 54 cut points with it and 53 without. Every cut point still
    // recovers to a state the campaign accepts.
    // **Ten fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 53 cut points before the change and 43 after. Every cut point
    // still recovers to a state the campaign accepts.
    // **Two fewer since a statement that only read keeps SHARED for the next
    // one (task-2197).** The statement after it takes no lock and reads no
    // meta record, and a lock and a read are each a cut point. Measured
    // through the campaign with the lease switched off: 43 cut points, and 41
    // with it. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-io-error.txt",
        shape: Shape::CutPoints,
        least: 41,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 88 cut points
    // became 80. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 80 cut points became 76 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 76
    // cut points, and 63 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 63 calls became 59. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 57 cut points became 59, and
    // 57 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `delete-full-crash.txt`, which runs the same workload, by putting each
    // change back in turn: 57 cut points before both, 54 with the meta slots
    // change alone, 57 with the header change alone, and 54 with both. Every
    // cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` on
    // `delete-full-crash.txt`, which runs the same workload, by putting the
    // sync back: 54 cut points with it and 53 without. Every cut point still
    // recovers to a state the campaign accepts.
    // **Ten fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 53 cut points before the change and 43 after. Every cut point
    // still recovers to a state the campaign accepts.
    // **Two fewer since a statement that only read keeps SHARED for the next
    // one (task-2197).** The statement after it takes no lock and reads no
    // meta record, and a lock and a read are each a cut point. Measured
    // through the campaign with the lease switched off: 43 cut points, and 41
    // with it. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-short-write.txt",
        shape: Shape::CutPoints,
        least: 41,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** 161 cut points became 153 over the same
    // commits that took eight from `delete-full-crash.txt`, where the eight
    // were traced to that change by running the campaign before and after it.
    // Every cut point still recovers to a state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 153 cut points became 149 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 149 calls became 145. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Four fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds twice. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 141 cut points became 145, and
    // 141 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Six fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 141 cut points before both, 138 with
    // the meta slots change alone, 138 with the header change alone, and 135
    // with both. Every cut point still recovers to a state the campaign
    // accepts.
    // **Two fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` by
    // putting the sync back: 135 cut points with it and 133 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Twenty two fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 133 cut points before the change and 111 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "truncate-full-crash.txt",
        shape: Shape::CutPoints,
        least: 111,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** 161 cut points became 153 over the same
    // commits that took eight from `delete-full-crash.txt`, where the eight
    // were traced to that change by running the campaign before and after it.
    // Every cut point still recovers to a state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 153 cut points became 149 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 149 calls became 145. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Four fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds twice. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 141 cut points became 145, and
    // 141 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **Six fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 141 cut points before both, 138 with
    // the meta slots change alone, 138 with the header change alone, and 135
    // with both. Every cut point still recovers to a state the campaign
    // accepts.
    // **Two fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` by
    // putting the sync back: 135 cut points with it and 133 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Twenty two fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 133 cut points before the change and 111 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "persist-full-crash.txt",
        shape: Shape::CutPoints,
        least: 111,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 55 cut points
    // became 47. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 47 cut points became 46 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 46
    // cut points, and 45 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 43 cut points became 45, and
    // 43 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **One fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 43 cut points before both, 43 with
    // the meta slots change alone, 42 with the header change alone, and 42 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` by
    // putting the sync back: 42 cut points with it and 41 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 41 cut points before the change and 29 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-checkpoint-crash.txt",
        shape: Shape::CutPoints,
        least: 29,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 55 cut points
    // became 47. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 47 cut points became 46 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 46
    // cut points, and 45 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 43 cut points became 45, and
    // 43 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **One fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `delete-full-checkpoint-crash.txt`, which runs the same workload, by
    // putting each change back in turn: 43 cut points before both, 43 with the
    // meta slots change alone, 42 with the header change alone, and 42 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` on
    // `delete-full-checkpoint-crash.txt`, which runs the same workload, by
    // putting the sync back: 42 cut points with it and 41 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 41 cut points before the change and 29 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-checkpoint-disk-full.txt",
        shape: Shape::CutPoints,
        least: 29,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 55 cut points
    // became 47. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 47 cut points became 46 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since a close shrinks the log only once the open segment holds a
    // mebibyte (task-2191).** A close still folds, and stopped rolling a new
    // segment, writing a checkpoint record and deleting the old segments every
    // time. Those calls came after the last commit was acknowledged. Measured by
    // making the close do the housekeeping again and running the campaign: 46
    // cut points, and 45 without it. Every cut point still recovers to a state
    // the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 43 cut points became 45, and
    // 43 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **One fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `delete-full-checkpoint-crash.txt`, which runs the same workload, by
    // putting each change back in turn: 43 cut points before both, 43 with the
    // meta slots change alone, 42 with the header change alone, and 42 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **One fewer since a rollback journal is synced before it is deleted only
    // when something was saved after its seal (task-2191).** The seal's sync
    // already covered every pre-image, so the second sync flushed nothing, and
    // every sync is a cut point. Measured through `inillucent-testrun` on
    // `delete-full-checkpoint-crash.txt`, which runs the same workload, by
    // putting the sync back: 42 cut points with it and 41 without. Every cut
    // point still recovers to a state the campaign accepts.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 41 cut points before the change and 29 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "delete-full-checkpoint-io-error.txt",
        shape: Shape::CutPoints,
        least: 29,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 54 cut points
    // became 46. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 46 cut points became 45 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 43 cut points became 45, and
    // 43 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **One fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `persist-full-checkpoint-crash.txt`, which runs the same workload, by
    // putting each change back in turn: 43 cut points before both, 43 with the
    // meta slots change alone, 42 with the header change alone, and 42 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 42 cut points before the change and 30 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "truncate-full-checkpoint-crash.txt",
        shape: Shape::CutPoints,
        least: 30,
    },
    // **Eight fewer since a bulk UPDATE repacks a leaf whose rows outgrow
    // their slots (task-2183).** Measured by running this campaign at the
    // commit before that change and at the change itself: 54 cut points
    // became 46. In
    // `delete-full-crash.txt` all eight were calls made after the commit was
    // acknowledged, which in this workload are the checkpoint's: the calls
    // before the commit are the same 33. Every cut point still recovers to a
    // state the campaign accepts.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 46 cut points became 45 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Two fewer since a fold under a rollback journal syncs once
    // (task-2191).** A fold synced the data file after its pages, then
    // journaled the two meta slots, synced the journal again, wrote the
    // slots and synced the data file a second time. The slots' pre-images
    // now go into the journal with the pages', so one journal sync and one
    // data file sync cover both, and each was a cut point. This workload
    // folds once. Measured by putting the previous `pool/fold.rs` back
    // and running the campaign again: 43 cut points became 45, and
    // 43 with this change. Every cut point still recovers to a state the
    // campaign accepts.
    // **One fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 43 cut points before both, 43 with
    // the meta slots change alone, 42 with the header change alone, and 42 with
    // both. Every cut point still recovers to a state the campaign accepts.
    // **Twelve fewer since a rollback journal writes its records and its header
    // in one call at the seal (task-2191).** Each pre-image used to be one
    // write of the record and one of the header, and every write is a cut
    // point. A cut before the seal finds no page overwritten, which is what
    // the dropped cut points tested. Measured through `inillucent-testrun`:
    // 42 cut points before the change and 30 after. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "persist-full-checkpoint-crash.txt",
        shape: Shape::CutPoints,
        least: 30,
    },
    // **Three fewer since `BEGIN` became deferred (task-2173).** The
    // workload opens with `BEGIN`, which took the write lock itself before
    // the first `INSERT` did. It takes no lock now, and the campaign lost
    // three cut points, all of them `old`: the report
    // went from 24 old and 3 new to 21 old and 3 new. Every cut that lands
    // after the first write is still made.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 27 calls became 23. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 23 cut points before both, 20 with
    // the meta slots change alone, 23 with the header change alone, and 20 with
    // both. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "wal-commit.tsv",
        shape: Shape::HashCuts,
        least: 20,
    },
    // **Three fewer since `BEGIN` became deferred (task-2173).** The
    // workload opens with `BEGIN`, which took the write lock itself before
    // the first `INSERT` did. It takes no lock now, and the campaign lost
    // three cut points, all of them `old`: the report
    // went from 24 old and 3 new to 21 old and 3 new. Every cut that lands
    // after the first write is still made.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 27 calls became 23. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `wal-commit.tsv`, which runs the same workload, by putting each change
    // back in turn: 23 cut points before both, 20 with the meta slots change
    // alone, 23 with the header change alone, and 20 with both. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "wal-io-error.tsv",
        shape: Shape::HashCuts,
        least: 20,
    },
    // **Three fewer since `BEGIN` became deferred (task-2173).** The
    // workload opens with `BEGIN`, which took the write lock itself before
    // the first `INSERT` did. It takes no lock now, and the campaign lost
    // three cut points, all of them `old`: the report
    // went from 24 old and 3 new to 21 old and 3 new. Every cut that lands
    // after the first write is still made.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 27 calls became 23. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Three fewer since an open reuses the meta slots its bootstrap read and
    // a new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // on `wal-commit.tsv`, which runs the same workload, by putting each change
    // back in turn: 23 cut points before both, 20 with the meta slots change
    // alone, 23 with the header change alone, and 20 with both. Every cut point
    // still recovers to a state the campaign accepts.
    Floor {
        name: "wal-short-write.tsv",
        shape: Shape::HashCuts,
        least: 20,
    },
    // **Three fewer since `BEGIN` became deferred (task-2173).** The
    // workload opens with `BEGIN`, which took the write lock itself before
    // the first `INSERT` did. It takes no lock now, and the campaign lost
    // three cut points, all of them `old`: the report
    // went from 24 old and 3 new to 21 old and 3 new. Every cut that lands
    // after the first write is still made.
    // **Fewer since the staleness check reads only the shadow meta slot
    // (task-2181).** Each lock a statement takes outside a transaction made
    // two reads of the meta record and now makes one, and every read is a
    // cut point. Measured by putting the primary slot's read back, discarded,
    // and running the campaign again: 55 cuts became 53 without it and returned
    // exactly to the old count with it. Every cut point still recovers to a
    // state the campaign accepts.
    // **Four fewer since an open reads the file's first pages once and opens
    // the log segment once (task-2191).** The open read the 100 byte header
    // three times, to look for a SQLite file, a foreign format and the page
    // size, then read each meta page on its own: five reads, now one read of
    // the header and one of both meta pages. Recovery opened the last log
    // segment to read it and the writer opened it again to append; the
    // writer now appends through the handle recovery read with. Every read
    // and every open is a cut point. Measured by tracing every call the
    // unarmed run makes, on the commit before and on this one, and comparing
    // the two lists: 53 calls became 49. The four missing are three
    // of those five reads and the second open of the segment. Every cut
    // point still recovers to a state the campaign accepts.
    // **Four fewer since an open reuses the meta slots its bootstrap read and a
    // new log segment's header is not synced on its own (task-2191).** Every
    // read and every sync is a cut point. Measured through `inillucent-testrun`
    // by putting each change back in turn: 49 cut points before both, 46 with
    // the meta slots change alone, 48 with the header change alone, and 45 with
    // both. Every cut point still recovers to a state the campaign accepts.
    Floor {
        name: "wal-checkpoint.tsv",
        shape: Shape::HashCuts,
        least: 45,
    },
    Floor {
        name: "multi-database-commit.tsv",
        shape: Shape::Rows { heading: true },
        least: 63,
    },
    Floor {
        name: "multi-database-short-write.tsv",
        shape: Shape::Rows { heading: true },
        least: 63,
    },
    Floor {
        name: "wal-recovery-idempotent.tsv",
        shape: Shape::Rows { heading: true },
        least: 48,
    },
    Floor {
        name: "recovery-crash.txt",
        shape: Shape::Rows { heading: false },
        least: 48,
    },
];

/// Returns the crash directory.
fn directory() -> PathBuf {
    workspace_root().join("tests/crash")
}

/// Returns how many cut points a report says it covered.
///
/// `None` when the file's first line is not the shape its row says it is, which
/// is a campaign that changed its format without moving its floor - and that is
/// as much a silent loss as a shrinking count, because a header nothing can
/// read is a header nothing checks.
///
/// @param text - the file's contents
/// @param shape - how this report states its count
fn covered(text: &str, shape: Shape) -> Option<usize> {
    let mut lines = text.lines();
    match shape {
        Shape::CutPoints => {
            let first = lines.next()?;
            let rest = first.strip_prefix("cut points: ")?;
            let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
            digits.parse().ok()
        }
        Shape::HashCuts => {
            let first = lines.next()?;
            let rest = first.strip_prefix("# ")?;
            let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
            if !rest
                .get(digits.len()..)
                .is_some_and(|after| after.starts_with(" cuts:"))
            {
                return None;
            }
            digits.parse().ok()
        }
        Shape::Rows { heading } => {
            let rows = text.lines().filter(|line| !line.trim().is_empty()).count();
            let rows = if heading {
                rows.saturating_sub(1)
            } else {
                rows
            };
            (rows > 0).then_some(rows)
        }
    }
}

/// Reads one schedule, or says which one is missing.
///
/// @param name - the file's name
fn read(name: &str) -> String {
    let path = directory().join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "{} is not readable ({error}). A schedule that is gone is a campaign nobody is \
             grading; restore it by running the campaign that writes it.",
            path.display()
        )
    })
}

/// Every schedule still covers at least what it was accepted at.
///
/// **The one check this directory was always missing.** Every other guarantee
/// about these files is that they are reproducible, and that makes a diff the
/// review signal - but a reviewer reading a diff is not a test, and the number
/// that matters is one nobody re-derives.
#[test]
fn no_campaign_covers_less_than_it_was_accepted_at() {
    let mut shrunk: Vec<String> = Vec::new();
    let mut unreadable: Vec<String> = Vec::new();
    for floor in &FLOORS {
        let text = read(floor.name);
        let Some(found) = covered(&text, floor.shape) else {
            unreadable.push(format!(
                "{}: the first line is `{}`, which is not the shape this row expects",
                floor.name,
                text.lines().next().unwrap_or("<the file is empty>")
            ));
            continue;
        };
        if found < floor.least {
            shrunk.push(format!(
                "{}: covers {found}, accepted at {}",
                floor.name, floor.least
            ));
        }
    }
    assert!(
        unreadable.is_empty(),
        "these schedules no longer state their coverage in the shape this file reads:\n  {}\n\
         A campaign that changed its header changed what a reader can check, so move the row \
         here in the same commit.",
        unreadable.join("\n  ")
    );
    assert!(
        shrunk.is_empty(),
        "these campaigns cover fewer cut points than they were accepted at:\n  {}\n\
         A campaign that reports fewer cut points has stopped testing something. The first \
         version of the DELETE campaign reported 127 while causing thirteen crashes, because a \
         crash armed at a read did nothing. Find what stopped being armed rather than lowering \
         the floor; lower it only with the reason written next to it.",
        shrunk.join("\n  ")
    );
}

/// And a campaign that grows takes its floor with it.
///
/// The companion, and the reason the floor does not rot. A campaign that covers
/// far more than its floor is one whose floor stopped meaning anything: it
/// would have to lose most of its coverage before anybody heard about it.
///
/// The slack is generous on purpose. What is being caught is a floor left
/// behind by a redesign, not a run that covered two more cut points.
#[test]
fn no_floor_is_left_far_below_what_the_campaign_covers() {
    let mut stale: Vec<String> = Vec::new();
    for floor in &FLOORS {
        let text = read(floor.name);
        let Some(found) = covered(&text, floor.shape) else {
            continue;
        };
        if found > floor.least.saturating_mul(2) {
            stale.push(format!(
                "{}: covers {found}, floor still {}",
                floor.name, floor.least
            ));
        }
    }
    assert!(
        stale.is_empty(),
        "these floors are less than half what the campaign now covers, so they would not \
         notice most of it going away:\n  {}\n\
         Raise the floor in the same commit as the campaign that earned it.",
        stale.join("\n  ")
    );
}

/// Every file in the directory is one this guard reads.
///
/// **Without this, adding a campaign is how the guard stops covering the
/// directory**, and it stops silently: a new schedule with no row here is a
/// campaign nothing holds a floor for, and every check above still passes.
#[test]
fn every_schedule_has_a_floor() {
    // `README.md` is prose about the directory, and `allocation.txt` records a
    // count of zero by design - see `FLOORS`.
    const NOT_A_SCHEDULE: [&str; 2] = ["README.md", "allocation.txt"];

    let mut unguarded: Vec<String> = Vec::new();
    let entries = std::fs::read_dir(directory()).expect("tests/crash is readable");
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|part| part.to_str()) else {
            continue;
        };
        if NOT_A_SCHEDULE.contains(&name) {
            continue;
        }
        if !FLOORS.iter().any(|floor| floor.name == name) {
            unguarded.push(name.to_string());
        }
    }
    assert!(
        unguarded.is_empty(),
        "these schedules have no floor in this file, so nothing notices when their campaign \
         shrinks:\n  {}\n\
         Add a row with the count the campaign covers today.",
        unguarded.join("\n  ")
    );
}

/// And every row names a file that is there.
///
/// The other direction, so a renamed campaign fails here rather than leaving a
/// row that matches nothing and guards nothing.
#[test]
fn every_floor_names_a_schedule() {
    let missing: Vec<&str> = FLOORS
        .iter()
        .map(|floor| floor.name)
        .filter(|name| !directory().join(name).is_file())
        .collect();
    assert!(
        missing.is_empty(),
        "these rows name a schedule that is not in tests/crash:\n  {}",
        missing.join("\n  ")
    );
}

/// No schedule carries a carriage return.
///
/// **This is the churn** (task-2066 §4.4.9). The campaigns write LF through
/// `std::fs::write`; `core.autocrlf` is true here, so before
/// `/tests/crash/** text eol=lf` was in `.gitattributes` git checked these
/// files out with CRLF and the first durability run of the day rewrote all
/// twenty-one of them. `git diff` showed nothing and `git status` showed
/// twenty-one modified files, which is the worst of both: nothing to review,
/// and a dirty tree that `packaging/ship.ps1` and `cargo publish` both refuse.
///
/// Asserting on the bytes rather than on `.gitattributes` holds whatever the
/// rule is written as, and it fails on the machine where it matters rather than
/// on the one where the rule was typed.
#[test]
fn no_report_carries_a_carriage_return() {
    let mut carrying: Vec<String> = Vec::new();
    let entries = std::fs::read_dir(directory()).expect("tests/crash is readable");
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Ok(bytes) = std::fs::read(&path) else {
            continue;
        };
        if bytes.contains(&b'\r') {
            carrying.push(name_of(&path));
        }
    }
    assert!(
        carrying.is_empty(),
        "these schedules carry a carriage return:\n  {}\n\
         The campaigns write LF, so a CRLF file is rewritten by the first run that touches it \
         and the tree is dirty with an empty diff. `.gitattributes` holds \
         `/tests/crash/** text eol=lf` for this; if it is still there, the working tree needs \
         converting once with `git add --renormalize tests/crash/`.",
        carrying.join("\n  ")
    );
}

/// The allocation report says why it is empty, rather than just being empty.
///
/// `points: 0, refused: 0` is a true statement about the shipping engine and a
/// useless one on its own: it is what a campaign that never armed anything also
/// writes. The second line is what tells them apart, and §4.4.12 files routing
/// the write path's allocations through `inillucent_base::buffer` so the
/// failpoint reaches them and the number stops being zero.
#[test]
fn the_allocation_report_says_why_it_is_empty() {
    let text = read("allocation.txt");
    let why = text.lines().nth(1).unwrap_or_default();
    assert!(
        !why.trim().is_empty(),
        "allocation.txt records a count of zero and does not say why, which is \
         indistinguishable from a campaign that armed nothing:\n{text}"
    );
    assert!(
        why.contains("buffer"),
        "allocation.txt's reason no longer names where the write path would have to allocate \
         for the failpoint to reach it, so a reader cannot tell the zero from a broken \
         campaign:\n{why}"
    );
}

/// Returns a path's file name for a message.
///
/// @param path - the file
fn name_of(path: &Path) -> String {
    path.file_name()
        .map(|part| part.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.display().to_string())
}
